# Usa la imagen oficial de Python como base
FROM esva-base-backend

# Copiar el directorio actual al contenedor en /usr/src/app
COPY . /workspaces

# Establecer el directorio de trabajo
WORKDIR /workspaces

# Exponer el puerto en el que Flask se ejecutará dentro del contenedor
EXPOSE 5000

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Ejecuta el script api.py al iniciar el contenedor
CMD [ "python", "-m", "flask", "run", "--host=0.0.0.0" ]