# Uses the official Python image as a basis
FROM python:3.11-slim

# Copy current directory to container in /usr/src/app
COPY . /workspaces

# Establish the working directory
WORKDIR /workspaces

# Expose the port on which Flask will run inside the container
EXPOSE 5000

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the api.py script at container startup
CMD [ "python", "-m", "flask", "run", "--host=0.0.0.0" ]